spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  
server:
  port: ${PORT:5000}
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

email:
  host: ${EMAIL_HOST}
  port: ${EMAIL_PORT}
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}

attachment:
  max-size: 10485760  # 10MB i bytes
  allowed-types:
    - image/jpeg
    - image/png
    - image/gif
    - application/pdf
    - application/msword
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document 

google:
  translate:
    api-key: ${GOOGLE_TRANSLATE_API_KEY}

encryption:
  key: ${ENCRYPTION_KEY} 